# -*- coding: utf-8 -*-
"""Escape Characters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U86HDgWLnEyJOYWU-_lr-jzuw52Fx473
"""

print ('Dia berkata : "Pergilah!"')

print ("Aku menimpali: \"Apakah kau ingin aku 'angkat kaki'?!\"")

print ("\\(^_^)/ (\\-_-/)")