# -*- coding: utf-8 -*-
"""JenisTipeData_KharismaMauly071.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlckyTkBc-ndXEmiBjDI2_gSdZJywX_G

MEMERIKSA JENIS TIPE DATA
"""

nama = 'moli'
usia = 19
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

"""KONVERSI TIPE DATA

"""

usia =input('masukkan usia anda ')
print(type(usia))

"""KONVERSI TIPE DATA SECARA NUMERIK

"""

panjang = int(input('masukkan panjang: '))
lebar = float(input('masukkan lebar '))
print('Luas =', panjang * lebar)

"""KONVERSI NUMERIK KE STRING"""

nama ="kharisma mauly"
tahun_lahir = 2006
print(nama + ' lahir ditahun ini ' + str(tahun_lahir))