# -*- coding: utf-8 -*-
"""Manipulasi_string_3_KharismaMauly_071

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVOOIxRtV7iwO2yqcCpz97ZQeug52Lor
"""

template = 'Halo, saya %s dari %s'

print(template % ('Kharisma Mauly', 'Indonesia'))

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template.format(nama = 'Kharisma Mauly', asal = 'Lampung'))
print(template_2.format('nasi goreng', 'teh'))

nama = 'Kharisma Mauly Abrar Iman'
asal = 'Lampung'

print(f'Perkenalkan saya {nama} dari {asal}')

alamat = 'Lampung Selatan, Lampung, Indonesia'

print(alamat.split())
#['Metro,','Lampung', 'Selatan,','Indonesia]

print(alamat.split())

print('💋'.join(['aku', 'suka', 'sushi']))

print('halo selamat malam!'.upper())
print('halo selamat makan!'.upper())

print('APA KABAR?'.lower())
print('Sudah Makan?'.lower())

print('daun tidak pernah membenci angin',title())
print('LASKAR PELANGI',title())

print('Indonesia Adalah Negara Kepulaian'.swapcase())
print('aKu cInTa NeGeRiKu'.swapcase())

angka = '12345'

print('Index angka 3:',angka.find('3'))
print('Index angka 45:',angka.find('45'))
print('Index angka 35:',angka.find('35'))

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', '🧟‍♀'))

paragraf = 'Baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')

print(f'Kata"di" muncul sebanyuak {x} kali')

paragraf = "Baru-baru ini telah ditemukan sebuah meteor di suatu sungai"

print(paragraf.count('di'))