# -*- coding: utf-8 -*-
"""UTS_Compro II_Kelompok 12 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19STRx5Srl2cUxKIcB7GtfkVNcM6ArKYf

**UTS COMPUTER PROGRAMMING 2**

Kelompok 12:

1. Dwi Junita Putri (2411012062)
2. Ajeng Ayu Maulidiah (2451012012)
3. Vegard Rajwa Aryaputra Fizali (2451012015)
4. Kharisma Mauly Abrar Iman (2411012071)
5. Muhammad Asra (2451012027)
"""

#Memisahkan 2 String Menggunakan Fungsi 'string.split()'
raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"
transaksi = (raw_log.split(';'))

#Membuat List Kososng Untuk Output Hasil
hasil_akhir = []
total_semua = 0

#Proses Memisahkan String "#" Menggunakan Fungsi 'string.split'
for trx in transaksi:
    bagian = trx.split('#')

#Membuat List 'sementara' Untuk Proses Penghapusan Variabel
    sementara = []

#Membuat Loop yang Mengulangi Setiap B dari Baris Pada Variabel 'bagian' dan Menghapus Spasi Pada b
    for b in bagian:
        teks = b.strip()

#Menghapus Variabel string 'ID', 'NAMA', 'QTY", dan 'PRICE' Menggunakan Fungsi string.replace()
        if "ID:" in teks:
            teks = teks.replace("ID:", "")
        elif "NAMA:" in teks:
            teks = teks.replace("NAMA:", "")
        elif "QTY:" in teks:
            teks = teks.replace("QTY:", "")
        elif "PRICE:" in teks:
            teks = teks.replace("PRICE:", "")

        sementara.append(teks)

#Menginput Setiap Variabel String Sesuai Dengan List 'sementara'
    nama_menu = sementara[1].title()
    jumlah_beli = int(sementara[2])
    harga_satuan = int(sementara[3])

#Operasi Penghitungan Subtotal (total_item) dan Total Keseluruhan (total_semua)
    total_item = jumlah_beli * harga_satuan
    total_semua += total_item

#Memasukkan Semua Variabel yang Sudah Dibersihkan
    hasil_akhir.append([nama_menu, jumlah_beli, harga_satuan, total_item])

#Output Hasil
print("=" * 60)
print(f"{'LAPORAN HARIAN KEDAI SOU SPACE':^60}")
print("=" * 60)
print(f"{'NAMA MENU':<30} {'QTY':<5} {'PRICE':<10} {'SUBTOTAL':<10}")
print("-" * 60)
for data in hasil_akhir:
    print(f"{data[0]:<30} {data[1]:<5} {data[2]:<10} {data[3]:<10}")
print("-" * 60)
print(f"{'TOTAL PENDAPATAN':<42} {total_semua:>10}")
print("=" * 60)